import moment from "moment";

export const tableData_E = [
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Akanbi",
    product: "DPK",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Akanbi",
    product: "DPK",
    liters: "20.5",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Akanbi",
    product: "DPK",
    liters: "20.5",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    price: "15,000.00",
    station: "Amaco Owerri",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Jain Odera",
    product: "DPK",
    liters: "20.5",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    price: "15,000.00",
    station: "Amaco Aba",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Jain Odera",
    product: "DPK",
    liters: "20.5",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    price: "15,000.00",
    station: "Amaco Umuahia",
    attendant: "Chinasa Udeka",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Akanbi",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    account_name: "Olumide Olaseun",
    product: "AGO",
    liters: "20.5",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    product: "AGO",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
];

export const tableData_S = [
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    vehicle_no: "JK-1234-3",
    product: "DPK",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Olumide Olaseun",
    vehicle_no: "JK-1234-3",
    product: "AGO",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Mike Kola",
    vehicle_no: "JK-1234-3",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Chi Chijioke",
    vehicle_no: "JK-1234-3",
    product: "AGO",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Chi Chijioke",
    vehicle_no: "JK-1234-3",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Chi Chijioke",
    vehicle_no: "JK-1234-3",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Chi Chijioke",
    vehicle_no: "JK-1234-3",
    product: "AGO",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Para Chijioke",
    vehicle_no: "JK-1234-3",
    product: "PMS",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Jata Chijioke",
    vehicle_no: "JK-1234-3",
    product: "DPK",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
  {
    id: `${Math.random()}`,
    date: moment().format("MMM Do YY"),
    time: moment().format("LT"),
    account_name: "Maku Chana",
    vehicle_no: "JK-1234-3",
    product: "AGO",
    liters: "20.5",
    price: "15,000.00",
    image:
      "https://media.geeksforgeeks.org/wp-content/uploads/20210425000233/test-300x297.png",
    station: "Amaco Uka",
    attendant: "Amina Ojo",
  },
];
